# Nova URL do serviço MoneyLens
spring.datasource.url=jdbc:mysql://moneylens-cadumcarlos-04ff.c.aivencloud.com:28276/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
# Use a senha nova do serviço MoneyLens
spring.datasource.password=AVNS_K61WqhPXEoHqv7D-LpW
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
